[tools]
golang = '1.24'
python = '3.13'

[tasks."llm:generate_bundle"]
description = 'Generate LLM bundle output file using repomix'
hide = true # hide this task from the lis
run = """
#!/usr/bin/env bash
npx repomix --style xml --output-show-line-numbers --output /tmp/output.txt --ignore **/uv.lock,**/package-lock.json,**/.env,**/Cargo.lock,**/node_modules,**/target,**/dist,**/build,**/output.txt,**/yarn.lock
"""

[tasks."llm:clean_bundles"]
description = 'Generate LLM bundle output file using repomix'
run = """
#!/usr/bin/env bash
find /tmp -name "output.txt" -print -delete
"""

[tasks."llm:generate_readme"]
depends = ["llm:generate_bundle"]
description = 'Generate README.md from repository content stored in output.txt using LLM generation'
run = """
#!/usr/bin/env bash
cat /tmp/output.txt | llm -t readme-gen > README.md
"""

[tasks."llm:copy_buffer_bundle"]
depends = ["llm:generate_bundle"]
description = 'Copy generated LLM bundle from output.txt to system clipboard for external use'
run = """
#!/usr/bin/env bash
cat /tmp/output.txt | pbcopy
echo "Pushed output.txt to the copy buffer"
"""

[tasks."llm:generate_tasks"]
depends = ["llm:generate_bundle"]
description = 'Generate Jira tasks from repository content stored in output.txt using LLM generation'
run = """
#!/usr/bin/env bash
cat /tmp/output.txt | llm -m claude-3.5-sonnet -t issue-gen > issues.md
"""

[tasks."llm:generate_code_review"]
depends = ["llm:generate_bundle"]
description = 'Generate code review output from repository content stored in output.txt using LLM generation'
run = """
#!/usr/bin/env bash
cat /tmp/output.txt | llm -m claude-3.5-sonnet -t code-review-gen > code-review.md
"""

[tasks."llm:generate_missing_tests"]
depends = ["llm:generate_bundle"]
description = 'Generate missing tests for code in repository content stored in output.txt using LLM generation'
run = """
#!/usr/bin/env bash
cat /tmp/output.txt | llm -m claude-3.5-sonnet -t missing-tests-gen > missing-tests.md
"""

[tasks."llm:generate_task_prompts"]
depends = ["llm:generate_bundle"]
description = 'Generate issue prompts from repository content stored in output.txt using LLM generation'
run = """
#!/usr/bin/env bash
cat /tmp/output.txt | llm -m o3-mini -t issue-prompts-gen > issue-prompts.md
"""

